Added optional passphrase for client certificates
Nyr/openvpn-install pull request #1029
Opened 2023-03-07 03:18 UTC by abn0mad

Added optional passphrase for client certificates during both initial install and later certificate generation. Created after looking for a way to add passphrases for client certificates and finding #1019

2023-04-16 23:15 UTC, toniGrabulosa requested changes

2023-04-16 23:15 UTC, toniGrabulosa commented on openvpn-install.sh
> +	read -e -p "Require password for client certificate [Y/N]: " -i "N" PASSW
I would remove the default "N" on the prompt.

So i suggest this:
```suggestion
	read -e -p "Require password for client certificate [y/N], default is [N]: " PASSW
```

2023-04-16 23:15 UTC, toniGrabulosa commented on openvpn-install.sh
> +	        read -e -p "Require password for client certificate [Y/N]: " -i "N" PASSW
Same as above.

2023-04-22 12:22 UTC, Nyr commented
Check previous duplicate issues on this matter. I have no interest in merging this feature.

2023-04-22 12:22 UTC, closed without merging